# MoritzLaurer/mDeBERTa-v3-base-xnli-multilingual-nli-2mil7
# google/t5_xxl_true_nli_mixture
# facebook/bart-large-mnli
# microsoft/deberta-v2-xlarge-mnli
# khalidalt/DeBERTa-v3-large-mnli
# typeform/distilbert-base-uncased-mnli
# roberta-large-mnli
# microsoft/deberta-v2-xxlarge-mnli
# sileod/deberta-v3-large-tasksource-nli
# cross-encoder/nli-deberta-v3-small
# cross-encoder/nli-deberta-v3-base
# cross-encoder/nli-deberta-v3-large
# cross-encoder/nli-roberta-base
# cross-encoder/nli-deberta-v3-large
# cross-encoder/nli-distilroberta-base
