openapi: 3.0.0
info:
  title: Language Model API
  description: API for generating text based on prompts using pre-trained language models.
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
    description: API server for language model text generation
paths:
  /complete:
    post:
      summary: Generates text based on a given prompt and optional parameters
      operationId: generateText
      tags:
        - Text Generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: Input prompt for the text generation model.
                decoding_strategy:
                  type: string
                  description: Strategy to use for decoding the generated text. Defaults to "generate".
                  enum: [generate, greedy_search, beam_search, sample, top_k, top_p]
                  default: "generate"
                max_new_tokens:
                  type: integer
                  description: Maximum number of new tokens to generate.
                do_sample:
                  type: boolean
                  description: Whether to use sampling for generation.
                temperature:
                  type: number
                  description: Temperature for sampling, controlling the randomness of predictions by scaling the logits before applying softmax.
                top_k:
                  type: integer
                  description: The number of highest probability vocabulary tokens to keep for top-k-filtering.
                top_p:
                  type: number
                  format: float
                  description: Nucleus filtering (top-p) cumulative probability. Keeps the top tokens with cumulative probability >= top_p.
                num_return_sequences:
                  type: integer
                  description: The number of sequences to return. Defaults to 1.
              required:
                - prompt
      responses:
        200:
          description: Successful response with generated text
          content:
            application/json:
              schema:
                type: object
                properties:
                  prompt:
                    type: string
                    description: The original prompt that was provided.
                  completion:
                    type: string
                    description: The generated text based on the prompt.
                  args:
                    type: object
                    description: The arguments that were used for the generation.
        400:
          description: Bad request, e.g., missing required fields
        500:
          description: Internal server error, e.g., model failed to generate text
